version: '3.4'

services:
  al-dente.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_HTTPS_PORTS=8001
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ~/Library/Application\ Support/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https